purestorage/pso-csi

CHANGELOG.md
**Summary of changes:**
* add CHANGELOG.md
=> [NO-ISSUE] Add CHANGELOG.md

pureStorageDriver/templates/plugin/configmap.yaml
Small change. Update the `configmap.yaml`
=> [ISSUE-9] Fix configmap check

README.md, docs/eks-multipathd-fix.md
Adding a note to help if someone using EKS and EBS.
=> add documentation for multipath on EKS

pureStorageDriver/README.md
* Will validate again when k8s 1.17 is available on GKE
=> [NO-ISSUE] Update Anthos support doc for 6.0

pureStorageDriver/snapshotclass.yaml
=> [NO-ISSUE]remove volumeBindingMode from snapshotclass

pureStorageDriver/templates/database/cockroach-operator.yaml
This is a corollary to #32, and is in tandem with another PR on cockroach-operator.
=> [NO-ISSUE] Added secret names to cockroach-operator

docs/csi-controller-attach-detach.md, pureStorageDriver/README.md, pureStorageDriver/values.yaml
* Removed empty "arrays" section as it conflicts with commented example
* @sdodsley I'd like some feedback on if you think this is correct or not. I can see valid reasons for commenting it out (like if you're the type of person to uncomment examples and change them), and valid reasons to keep the empty `arrays` entries (like if you're the kind of person to copy from examples but leave them commented).
* Added debugging info for taints and tolerations
* Fixed incorrect NFSEndpoint capitalization in examples
* Added an example `install` command to the basic install section
=> [NO-ISSUE] Updated documents after install feedback

README.md, docs/csi-controller-attach-detach.md, docs/csi-filesystem-options.md, docs/csi-qos-control.md, docs/csi-read-write-many.md, docs/csi-snapshot-clones.md, docs/csi-topology.md, docs/csi-volume-expansion.md, docs/csi-volume-import.md, docs/custom-storageclasses.md, docs/eks-multipathd-fix.md, pureStorageDriver/README.md
Remove all unnecessary references to k8s and PSO versions not supported by PSO 6
Consolidate READMEs into something more readable.
=> [NO ISSUE] Update docs to be more PSO 6.0 friendly

pureStorageDriver/templates/plugin/node-server.yaml
**Summary of changes:** 
* Add config map to node-server pods.
=> [NO-ISSUE] Add configmap to node-server pods

README.md, pureStorageDriver/README.md
**Please review both the changes, as well as the full pages [here](https://github.com/Pure-AdamuKaapan/pso-csi/tree/GADocUpdates/pureStorageDriver) and [here](https://github.com/Pure-AdamuKaapan/pso-csi/tree/GADocUpdates)**
Requested points to have accented:
* Fresh install (no upgrades) only: now present in `pureStorageDriver/README.md`
* `clusterID` is unique between clusters: already present in `pureStorageDriver/README.md`
* Minimum node requirements (3+ required, 5+ optimal): now present in both `README.md` and `pureStorageDriver/README.md`
* NTP/chrony requirements: already present in `pureStorageDriver/README.md`, now present in `README.md`
Also:
* Reorganized `pureStorageDriver/README.md` to be a little bit easier to follow
* Fixed various typos
* Removed cockroach DB legal …
=> [NO-ISSUE] Updated docs for GA release

pure-pso/README.md, pure-pso/templates/database/cockroach-operator.yaml, pure-pso/values.yaml
Adds configuration of the `psctl` image into the values file.
=> [NO-ISSUE] Added psctl image configuration

docs/csi-snapshot-import.md, docs/examples/snapshotimport/backend-content.yaml, docs/examples/snapshotimport/backend-snapshot.yaml, docs/examples/snapshotimport/import-pvc.yaml, docs/examples/snapshotimport/import-vol.yaml, docs/examples/snapshotimport/mount-pvc-to-pod.yaml, docs/examples/snapshotimport/pod-from-pvc-restore.yaml, docs/examples/snapshotimport/pvc-restore.yaml
=> [NSTK-2068] Docs & Example yamls for Snapshot Importing

CHANGELOG.md
ISSUE-90 fixed in PR#94, but not included in CHANGELOG.
=> [NSTK-2067] fix release changelog

CHANGELOG.md
=> [NSTK-2067] add REST 2.0 to release changelog

pure-pso/README.md
**Summary of changes**
* Add explanation for memory and CPU usage for db-pods
* Address the concerns of the #91
=> [ISSUE-91] Add explanation for memory and CPU usage for db-pods

pure-pso/templates/database/cockroach-operator.yaml, pure-pso/templates/database/db-deployer.yaml
=> [NSTK-2072] fixed "log level in values.yaml not hornored"

docs/99-pure-storage-attach.yaml, docs/openshift_mc.md
Update docs to explain how to disable iSCSI from the OpenShift machineconfig YAML file.
Add comments into YAML file for explanation
=> ISSUE] Update to allow for different protocol granularity

docs/csi-5to6-upgradepath.md, pure-pso/README.md
Add docs for upgrade process and link from main README.
Clean main README in existing upgrade section
=> [NO-NSTK] Add PSO 5 to 6 Upgrade docs

scripts/patch-smart-agent.sh, scripts/pso-network-debug.sh
Tested on a cluster with non default namespace for PSO
=> Fix: endpoint namespace incorrect

docs/openshift_mc.md, pure-pso/README.md
Add more details for successful OpenShift installation
=> Add more OpenShift installation details

README.md
**Summary: **
*   update support@purestorage.com email support
=>  [NO-NSTK] update support@purestorage.com email support

README.md
**Summary of changes:**
*  update pso-tses@purestorage.com email support
=> [NO-NSTK] update pso-tses@purestorage.com email support

README.md
=> add requirement for user_friendly_names setting in multipath configuration.
