purestorage/pso-csi

docs/csi-controller-attach-detach.md
Documents how to restrict where various pods run, as well as provides a couple small examples. I didn't add them to the `examples` directory since they're `values.yaml` examples, not pod/PVC examples.
=> [NO-ISSUE] Added controller-based attach-detach docs

pureStorageDriver/templates/database/rbac.yaml
This allows the cockroach-operator to run decommission commands.
=> [NO-ISSUE] Allow pso-db-runner role to pod exec

pureStorageDriver/values.yaml
Suggest to correct indentation for `arrays:` example to avoid copy/paste issues.
=> Suggest correct indentation for arrays example

pureStorageDriver/templates/database/cert-secret.yaml
This fixes these certificates not being cleaned up by a `helm del`. My guess is that these annotations were included when we used Helm 2 which might have treated secrets differently. Regardless, I tested with a manual uninstall and everything worked as expected.
=> [NO-ISSUE] Removed Helm hook from cert secrets

pureStorageDriver/templates/database/rbac.yaml
Previously, cockroach-operator would sometimes throw errors on API server restarts, saying that it couldn't watch ServiceAccounts, Roles, and RoleBindings. We don't do any watches from cockroach-operator on them, but my guess is that when we set owner references it adds a watch (which is set up automatically at the beginning, but might need a refresh on API server restarts).
=> [NO-ISSUE] Fixed cockroach-operator watch RBAC

pureStorageDriver/templates/database/cert-secret.yaml
Turns out that, while this worked great for initial installs and `helm delete`s, it breaks on upgrades. I'm developing an alternative, code-based solution.
=> Revert "[NO-ISSUE] Removed Helm hook from cert secrets"

pureStorageDriver/templates/database/rbac.yaml, pureStorageDriver/templates/plugin/scc.yaml, pureStorageDriver/values.schema.json
Adds a SecurityContextConstraints object for when `Values.plugin.orchestrator` is set to `openshift`. Also fleshes out the values schema to restrict this value to either `k8s` or `openshift`.
Also updates our existing RBAC objects with the following changes:
* Allows updating of secret finalizers
* Allows deletion of our ServiceAccount, Role, and RoleBinding
This has not yet been tested on a physical OpenShift cluster, and more debugging work is being done. Mainly opening this PR for visibility and ease of testing (@sdodsley once you get a chance), it will likely require more edits as time goes on.
Addresses #40.
=> [ISSUE-40] Added extra RBAC to match stricter OSE requirements

pureStorageDriver/templates/plugin/controller-server.yaml, pureStorageDriver/templates/plugin/node-server.yaml, pureStorageDriver/templates/plugin/rbac.yaml, pureStorageDriver/templates/plugin/storage-class.yaml
* since PSO 6.0+ require k8s 1.17+, some k8s version checks are no longer needed.
=> [NO-ISSUE] Delete useless k8s version checks

pureStorageDriver/README.md
Changing `clusterID` can cause unexpected things to happen. 
Until we can find some way to block customers changing this with `helm upgrade` we need to add this warning
=> Add warning about not changing clusterID

pureStorageDriver/templates/database/cockroach-operator.yaml, pureStorageDriver/templates/plugin/rbac.yaml, pureStorageDriver/templates/plugin/scc.yaml
Adds a few things I missed from before:
* Adds an SCC name variable to the cockroach-operator for OpenShift deployments only
* Adds the necessary ClusterRole and ClusterRoleBinding to allow cockroach-operator to own the SCC
* Makes the SCC not get removed with `helm del`
=> [ISSUE-40] Added more missing OpenShift security objects

pureStorageDriver/templates/database/cockroach-operator.yaml, pureStorageDriver/templates/database/db-deployer.yaml, pureStorageDriver/templates/plugin/rbac.yaml, pureStorageDriver/templates/plugin/scc.yaml
Mounts the PSO ConfigMap into the db-deployer, enabling it to use the configmap settings in database volumes.
Also fixes a formatting error from the last PR.
Closes #55.
=> [ISSUE-55] Enables setting export rules for database volumes

pureStorageDriver/templates/database/cockroach-operator.yaml, pureStorageDriver/templates/database/rbac.yaml, pureStorageDriver/templates/plugin/rbac.yaml
* Makes the cockroach-operator pod privileged to be able to read the cert secrets as root (previous functionality "worked" but couldn't check the DB for health metrics)
* Changed `SecurityContextConstraint` RBAC so all SCCs can be watched, not just `pso-scc`
* Reformatted so that all RBAC files have the same list format (some were using array notation, some were using "hyphen list" notation)
=> [NO-ISSUE] RBAC fixes for OSE 4.5

pure-pso/templates/plugin/controller-server.yaml
This is necessary for the DB reconstructor to find itself and all of the relevant nodes.
Not a blocker for GA.
=> [NO-ISSUE] Added the k8s namespace to the controller server

pure-pso/values.yaml
Based on recent feedbacks, I observed we replaced db volume many times unnecessarily, hence increase the grace period, so we give more time before we replace db volume, good for cases of rolling upgrade etc
=> [NO-ISSUE] change default grace period before replacing db volume

README.md, docs/99-pure-storage-attach.yaml, docs/openshift_mc.md
This PR adds documentation for OpenShift to ensure that multipath and iSCSI are correctly configured and enabled on worker nodes.
It adds the recommended multipath configuration information for Pure devices as well as applying the recommended udev settings
These setting are for RHEL7 and RHCOS.
when RHEL8 is supported by OpenShift these will need to be updated
=> Add pre-reqs for OpenShift

mirror_pso_containers.sh, pure-pso/README.md
Add a simple script to pull the images PSO requires and push them into a local registry.
Update README to reference this script.
This will need to be updated as part of each PSO release cycle with new image tags
=> [NO_ISSUE] Add script to mirror images to local registry

pure-pso/templates/database/cockroach-operator.yaml, pure-pso/templates/plugin/cert-secret.yaml, pure-pso/templates/plugin/controller-server.yaml, pure-pso/templates/plugin/node-server.yaml
This PR enables inline ephemeral volume support in our driver during deployment, and generates new certificate for CSI/gRPC calls. The reason is in inline volume there is only CSI node API call, our CSI node does not have permit to create volume so we need to let CSI node call CSI controller API with cert auth.
This cert can be used for other purposes too, like the snapshot policy controller Jiafeng and David are working on.
=> [NSTK-1931] CSI Ephemeral Local Volume + Enable gRPC cert

docs/custom-storageclasses.md, pure-pso/README.md
`pure` storage class has been removed in PSO 6.
This PR removes all trailing references to this storage class and the ability to set a default storageclass in the PSO configuration.
=> [ISSUE-87] Remove deprecated storageClass

pure-pso/templates/database/cockroach-operator.yaml, pure-pso/templates/database/db-deployer.yaml
This is for issue #90, the last fix didn't work, this fix was verified manually. 
Cockroach DB is default to INFO level, so no change needed for it. This is fixing
=> [ISSUE#90]Debug level not set right for cockroach and dbdeployer

docs/csi-5to6-upgradepath.md, pure-pso/templates/plugin/configmap.yaml, pure-pso/templates/plugin/controller-server.yaml, pure-pso/templates/plugin/node-server.yaml, pure-pso/values.schema.json, pure-pso/values.yaml
1) increase livenessprobe threshold from 10 to 100 to allow db construction to finish before pods having to restart
2) add configmap for upgrade flag
=> [NO-NSKT] Upgrade path from PSO5 to 6

docs/openshift_mc.md
Ensure it is obvious you must change the `orchestrator` from the default of `k8s` to `openshift`
=> Add clarity for OpenShift deployments

pure-pso/templates/database/cockroach-operator.yaml, pure-pso/values.yaml
**Summary of changes**
* update cockroach-operator version to v1.2.0-pre for testing. It contains the node-config in the initContainer of the pso-db pods.
=> [NO-ISSUE] update cockroach-operator version to v1.2.0-pre for testing

pure-pso/values.yaml
For some reason, this got dropped from the file between PSO 5 and PSO 6
This is still needed to ensure that we correctly register the CSI driver if the default kubelet configuration file directory is not used by a deployment, eg Tanzu
This has been tested in a customer Tanzu environment and works as expected
=> Readd basePath parameter

pure-pso/values.yaml
This only applies to the new installation. Helm upgrage won't upgrade
the version.
=> Upgrade CockroachDB to v20.2.6

README.md
**Summary of changes:**
* Add the pso-support@purestorage.com as the default contact for any PSO supports.
=> [NO-NSTK] add pso-support@ email support

pure-pso/templates/database/cockroach-operator.yaml, pure-pso/values.schema.json, pure-pso/values.yaml
To fix [ISSUE-166](https://github.com/purestorage/pso-csi/issues/166)
=> [NEWSTACK-190] Add iSCSI CIDR to cockroack-operator pod

pure-pso/crds/pso_v1alpha1_intrusion_crd.yaml, pure-pso/templates/_helpers.tpl, pure-pso/templates/plugin/node-server.yaml
**Summary of changes:**
* update `additionalPrinterColumns`
* remove `version: v1alpha1` - old style
=> Update intrusions CRD v1 to be backward-compatible

scripts/pso-network-debug.sh
`ping -w 2` can report packet loss on a stable connection as ping is interrupted before receiving an answer. Using `ping -c 2`(count) instead.
=> Avoid packet loss when using ping
